import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "🥳Xy6Blog🥳",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={`${inter.className}`}>
        <div className="daisy-navbar bg-base-100">
          <Link href='/' className="pl-6">🥳Xy6Blog🥳</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
