import type { Metadata } from "next";
import { Inter, Lora, JetBrains_Mono, Noto_Serif_SC } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import "../components/font.css"
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
const lora = Lora({ subsets: ["latin"] });
const jetbrains_mono = JetBrains_Mono({ subsets: ["latin"] });
const noto_serif_sc = Noto_Serif_SC({ subsets: ["latin"], weight: "500" });
// JetBrainsMono_Vivosans
// Inter_Vivosans

export const metadata: Metadata = {
  title: "🥳Xy6Blog🥳",
  description: "Generated by create nextapp",
};

const VivoSans = localFont({
  src: [
    { path: "Font/vivoSans-Regular.ttf", weight: '500' },
    { path: "Font/vivoSans-Bold.ttf", weight: '700' },
  ],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={`JetBrainsMono_Vivosans`}>
        <div className="daisy-navbar bg-base-100">
          <Link href='/' className="pl-6">🥳Xy6Blog🥳</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
